### ISSUE TITLE
pytest-xdist support

### ISSUE THREAD

**Issue by timdiels** [tarpas/pytest-testmon#42] opened 2016-03-24 11:19 UTC
When combining testmon and xdist, more tests are rerun than necessary. I suspect the xdist runners don't update `.testmondata`.

Is testmon compatible with xdist or is this due to misconfiguration?

**Comment by tarpas** [comment] 2016-03-29 06:20
Hi, unfortunatelly testmon is not compatible with xdist.
ᐧ

On Thu, Mar 24, 2016 at 12:19 PM, Tim Diels <notifications@github.com>
wrote:

> When combining testmon and xdist, more tests are rerun than necessary. I
> suspect the xdist runners don't update .testmondata.
>
> Is testmon compatible with xdist or is this due to misconfiguration?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tarpas/pytest-testmon/issues/42>
>



-- 
Best,
Tibor
+421907266112
-----
www.infinit.sk - The Python development team
www.testmon.org  - taking automated Python tests to a new level

**Comment by boxed** [comment] 2016-11-29 08:12
Do you know what the problem is? If it's described in this ticket, maybe someone can take a look?

**Comment by tarpas** [comment] 2016-12-01 07:16
No I don't know what the problem is and it's not described anywhere. What do you expect from the combining xdist and testmon? Wha'ts your use case, please?

**Comment by boxed** [comment] 2016-12-01 08:43
The use case is the same as for xdist: if you have a lot of tests they can benefit from being run in parallel. 

So the scenario would be: 
1. you change some file and testmon detects 100 (slow integration) tests that needs to be run
2. testmon starts the tests with xdist enabled and the tests run in parallel

**Comment by tarpas** [comment] 2016-12-06 04:38
Ok, right. I'm currently thinking about lightning fast, CPU efficient, interactive re-execution of small test suites. (which wouldn't benefit because of the cost of starting-up multiple interpreters, and because of IPC)

When I said testmon is not compatible with xdist I meant I didn't test it and didn't invest the time to think about it. The problem is what @timdiels describes. After thinking about it here are my ideas:
If the slaves run at remote machine or in different directories, then .testmondata doesn't get the data from slaves. How to solve this?
pytest-testmon would have to send the coverage data to the master in similar fashion to what xdist does with reports:
https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/remote.py#L92

Poor man's solution for the cases when the slaves actually run on the same machine in the same directory, would be to just make sure the different processes don't overwrite each other, which I'm pretty sure is happening. To achieve that the .testmondata format would have to change, so that each nodedata is stored in a separate row of the "alldata" sqlite table. That would be a good change for a number of other reasons anyway.

**Comment by notestaff** [comment] 2017-06-20 19:47
"nodedata is stored in a separate row of the "alldata" sqlite table." -- concurrent writes would still be a problem, no?  Wouldn't you want to store each test node's data in a separate file, to avoid conflicts?

**Comment by tarpas** [comment] 2017-06-21 00:36
No, as far as I know it's fine and Sqlite takes care of everything better than I could manually https://stackoverflow.com/questions/4060772/sqlite3-concurrent-access

**Comment by notestaff** [comment] 2017-06-21 03:53
I've seen "database locked" errors with -n 2, that go away with disabling xdist.  Maybe, adding retries would fix that?

**Comment by notestaff** [comment] 2017-06-21 07:53
@tarpas btw I saw you held a fundraiser for this project.  I bet travis-ci would sponsor it, since it'd save them a done of computation if people used it in conjunction with travis' caching of specified directories between builds ( https://docs.travis-ci.com/user/caching/#Arbitrary-directories )

**Comment by tarpas** [comment] 2017-06-21 14:53
Is the "database locked" error the same as here?: https://github.com/tarpas/pytest-testmon/issues/68#issue-235156982 , if yes, it's been fixed in version 0.9.6

**Comment by tarpas** [comment] 2017-06-21 15:09
@notestaff About travis-ci: I know, right! :) I see some downsides however. Does anybody have a tip whom to contact at Travis-CI?

**Comment by blueyed** [comment] 2017-06-21 15:37
One downside appears to be that this won't work when collecting coverage for your tests, which is rather typical I assume?!
Also for CI it is more important to really run all tests (and not skipping some accidentally because of some potential issue with pytest-testmon or how the cache/data was synced etc).

**Comment by notestaff** [comment] 2017-06-22 20:03
You can save coverage info, e.g. as in https://github.com/notestaff/pytest-testmon/tree/is-save-cov
You give up sub-file resolution.

There are degrees of CI; for our use, we plan to skip tests for routine branch checkins and pull requests but clear the cache and run all tests for tagged releases.  The flipside of _not_ skipping tests is that you get wary of adding even meaningful tests to the test suite, since the commit-then-test cycle becomes too slow as the test suite grows.

**Comment by notestaff** [comment] 2017-06-22 20:05
For reference, list of related projects:
https://pypi.python.org/pypi/pytest-testmon
https://pypi.python.org/pypi/pytest-incremental
https://pypi.python.org/pypi/pytest-cov-exclude
https://pypi.python.org/pypi/pytest-cagoule
https://pypi.python.org/pypi/pytest-knows
https://pypi.python.org/pypi/pytest-skipper
https://github.com/ChrisBeaumont/smother

**Comment by blueyed** [comment] 2017-07-10 10:03
FWIW: pytest-incremental is also not compatible with xdist.

**Comment by blueyed** [comment] 2018-08-02 16:10
It would be awesome if `--testmon` could be used with xdists's `--looponfail`, which appears to keep (potentially remote) workers ready (but re-runs all (selected) tests then).
`--testmon` currently does not contribute to test deselection and appears to not be notified about failures correctly.
The first issue is the case with pytest's own `--lf/-ff` though already (https://github.com/pytest-dev/pytest-xdist/issues/326).

Are you using local "popen" workers/nodes, or something like `--tx ssh=…` also?

**Comment by crutcher** [comment] 2019-07-25 23:31
It appears that db locked errors trace to CREATING the sqllite db; the go away after the first run.

**Comment by jacksongoode** [comment] 2021-12-07 00:24
Support for xdist would be really nice - in the meantime has anyone found an alternative to run distributed tests on those whose coverage has changed?

**Comment by nrontsis** [comment] 2022-02-18 19:19
Has there been any progress with this? I would happy to contribute.

**Comment by tarpas** [comment] 2022-09-14 13:36
I'm working on this. There has been a couple of compatibility and performance challanges there should be a (pre)release within weeks.

**Comment by tarpas** [comment] 2022-09-16 16:12
v1.4 of pytest-testmon will have pytest-xdist support. pre releases are being published via pypi. ```pip install pytest-testmon --pre``` @nrontsis

**Comment by tarpas** [comment] 2022-10-26 10:31
This is now released.

**Closed by tarpas** 2022-10-26 10:31 UTC
Labels: enhancement
