### ISSUE TITLE
Change in data source passed with pytest.mark.parametrize does not cause test rerun

### ISSUE THREAD

**Issue by dutchgecko** [tarpas/pytest-testmon#115] opened 2018-09-24 15:04 UTC
Our testsuite has a number of tests which are run with parametrized data. The data source in turn is a variable (usually a list of some kind) in another module. When the data is altered, testmon fails to rerun the affected test.

Simple dummy project example:

#### File test_list.py:
``` python
import pytest
import data

@pytest.mark.parametrize("testdata", data.listdata)
def test_list(testdata):
    assert testdata
```

#### File data.py:
``` python
listdata = [
    True,
    True,
    True,
]
```

In this example, appending an item to `listdata` will not result in `test_list` being selected in the next test run.

Python version: 3.4.5
Pytest version: 3.8.1 (source: pip)
pytest-testmon version: 0.9.13 (source: pip)

**Comment by tarpas** [comment] 2018-09-24 15:45
Thanks for the clear bug report. At a first sight I think this is conceptual weakness of testmon and it might take longer to fix. I'll write more when I have more time.

**Comment by tarpas** [comment] 2019-10-03 20:18
@dutchgecko unfortunately won't fix (in the near future). It would be possible to react to the change but that would eliminate most of the potential time savings that testmon is designed to achieve. The (data) library is imported (and the data is initialized) before any test is run. Usually that's true for all tests and all files under test. We ignore what is executed during the import(collection) phase and assume dependency on any file in your project which executes at least on line from the setup, call or teardown phase of a test.

There is probably a workaround where you could make pytest execute a function during the setup phase to get the parametrization data:
https://raphael.codes/blog/pytest-parametrize-with-indirect/

It seems quite verbose and I don't have experience with it.

**Comment by tarpas** [comment] 2019-10-04 06:53
@dutchgecko or in a primitive, heavy handed but clearer way:
* to data.py add:
```
def ping():
    return 0
```
* and then call it from inside the test function: ```data.ping()``` The rest stays the same as in your original version

**Comment by tarpas** [comment] 2023-11-09 21:56
This is a duplicate of https://github.com/tarpas/pytest-testmon/issues/191 (which described the more general case)

**Closed by tarpas** 2023-11-09 21:56 UTC
