### ISSUE TITLE
How to diagnose testmon behavior

### ISSUE THREAD

**Issue by maxim-lian** [tarpas/pytest-testmon#95] opened 2018-04-20 00:39 UTC
Is there a way I can see why testmon chooses to run or not rerun a test?

I frequently have times where I change code that affects a test, but testmon doesn't rerun any tests. I'd like to ensure that I'm correct (and to help the project by submitting a more helpful issue than "this don't work!").

Is there a reasonable way for me to see what testmon believes are the lines of code should cause a test to be rerun?

**Comment by tarpas** [comment] 2018-04-21 05:51
Unfortunately there is no easy way. Closing this as duplicate of #62

**Closed by tarpas** 2018-04-21 05:51 UTC
