### ISSUE TITLE
If test itself changes, should testmon pick it up?

### ISSUE THREAD

**Issue by adam-mrozik** [tarpas/pytest-testmon#202] opened 2023-01-19 09:09 UTC
I have made a PR changing one test file only. Testmon, as a result, collected 0 tests. Is this expected? I assume if it is based on coverage, then this is expected, but kind of hinders some of the functionality, because now I have to run sum whatever pytest collects with whatever test files have been changed

**Comment by tarpas** [comment] 2023-01-19 10:28
Yes definitely it should pick it up.... Did you run something like `pytest --testmon --cov=src tests` ? So that tests are outside of the collected coverage? 

In that case it should work too, but there might have been a bug which will be fixed in 1.4.5.

**Comment by adam-mrozik** [comment] 2023-01-19 14:08
I run `python3 -m pytest etests --testmon-forceselect` (using forceselect + folder with tests is named different). Could any of these affect my results?

**Comment by pokopt** [comment] 2023-01-24 13:56
@adam-mrozik I'm trying to reproduce the issue but with no luck so far. Was your change "significant"? I mean did you change reachable code not just comment or so? Thanks in advance for more info.

**Comment by pokopt** [comment] 2023-02-01 15:05
Since I can't reproduce the problem I'm closing the issue. In case of any update I'll be happy to investigate further.

**Closed by pokopt** 2023-02-01 15:05 UTC
