### ISSUE TITLE
PytestRemovedIn9Warning: The (path: py.path.local) argument is deprecated, please use (collection_path: pathlib.Path)

### ISSUE THREAD

**Issue by Anton-Aracor** [tarpas/pytest-testmon#242] opened 2024-10-18 09:55 UTC
Please upgrade to the latest pytest style to avoid this bug:

```
~/.venv/lib/python3.12/site-packages/testmon/pytest_testmon.py:461: PytestRemovedIn9Warning: The (path: py.path.local) argument is deprecated, please use (collection_path: pathlib.Path)
see https://docs.pytest.org/en/latest/deprecations.html#py-path-local-arguments-for-hooks-replaced-with-pathlib-path
  def pytest_ignore_collect(self, path, config):
```

**Comment by Anton-Aracor** [comment] 2024-10-29 06:25
@tarpas do you plan to make adjustments? Thx

**Comment by ns-rse** [comment] 2024-11-01 12:31
@Anton-Aracor #241

**Comment by ndalchau** [comment] 2024-11-05 08:47
This issue is a duplicate of #237 . As @ns-rse pointed out, I have an PR waiting to be approved by @tarpas that fixes it.

**Comment by ndalchau** [comment] 2024-11-07 20:06
The PR has been merged, so I believe this issue can now be closed.

**Comment by tarpas** [comment] 2024-11-11 13:26
I'll close it once I do a release. Sorry for the delays, busy.

**Comment by danielsiwiec** [comment] 2024-12-21 15:31
@tarpas just checking in here - would love to see the new version released and get rid of the warnings 🙏  if there's anything I can do to help, I'm happy to!

**Comment by tarpas** [comment] 2024-12-22 12:55
released, sorry for the delay.

**Closed by tarpas** 2024-12-22 12:55 UTC
