### ISSUE TITLE
deleting code causes an internal exception

### ISSUE THREAD

**Issue by TauPan** [tarpas/pytest-testmon#61] opened 2017-03-22 14:26 UTC
I see this with pytest-testmon > 0.8.3 (downgrading to this version fixes it for me).

How to reproduce:

 - delete .testmondata
 - run `py.test --testmon` once
 - Now delete some code (in my case, it was decorated with `#  pragma: no cover`, not sure if that's relevant)
 - call `py.test --testmon` again
And look at a backtrace like the following
```python
===================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
Django settings: sis.settings_devel (from ini file)
testmon=True, changed files: sis/lib/python/sis/rest.py, skipping collection of 529 items, run variant: default
rootdir: /home/delgado/nobackup/git/sis/software, inifile: pytest.ini
plugins: testmon-0.9.4, repeat-0.4.1, env-0.6.0, django-3.1.2, cov-2.4.0
collected 122 items 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/main.py", line 132, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/main.py", line 141, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/main.py", line 602, in perform_collect
INTERNALERROR>     config=self.config, items=items)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/delgado/nobackup/virtualenvs/sis/lib/python2.7/site-packages/testmon/pytest_testmon.py", line 165, in pytest_collection_modifyitems
INTERNALERROR>     assert item.nodeid not in self.collection_ignored
INTERNALERROR> AssertionError: assert 'sis/lib/python/sis/modules/marvin/tests.py::TestGetEventIDsForAWID::test_should_fail_for_expired_events' not in set(['da-exchanged/lib/python/exchanged/tests/test_config.py::TestConfigOptions::test_should_have_default_from_addr', ...'da-exchanged/lib/python/exchanged/tests/test_config.py::TestGetExchanges::test_should_return_sensible_defaults', ...])
INTERNALERROR>  +  where 'sis/lib/python/sis/modules/marvin/tests.py::TestGetEventIDsForAWID::test_should_fail_for_expired_events' = <TestCaseFunction 'test_should_fail_for_expired_events'>.nodeid
INTERNALERROR>  +  and   set(['da-exchanged/lib/python/exchanged/tests/test_config.py::TestConfigOptions::test_should_have_default_from_addr', ...'da-exchanged/lib/python/exchanged/tests/test_config.py::TestGetExchanges::test_should_return_sensible_defaults', ...]) = <testmon.pytest_testmon.TestmonDeselect object at 0x7f85679b82d0>.collection_ignored

==================================================================================== 185 tests deselected =====================================================================================
=============================================================================== 185 deselected in 0.34 seconds ================================================================================
```

**Comment by tarpas** [comment] 2017-03-30 15:37
The "# pragma: no cover" is very likely relevant. Would anybody care to make a unit test for this case?

**Comment by TauPan** [comment] 2017-04-03 07:39
I might later, when I find the time (already crashed a deadline at the moment). Would it go into `test_testmon.py`?

**Comment by tarpas** [comment] 2017-04-03 13:15
Yes, test_testmon.py

**Comment by TauPan** [comment] 2017-05-02 14:46
Sorry, no idea how to proceed. Here's my cargo-culted attempt, but I have no idea what half of these things do and I'm probably testing the wrong thing altogether.

```python
def track_multiple(testdir, func, testmon=None, testmon_data=None):
    if testmon is None:
        testmon = CoreTestmon(project_dirs=[testdir.tmpdir.strpath],
                              testmon_labels=set())
    if testmon_data is None:
        testmon_data = CoreTestmonData(testdir.tmpdir.strpath)
    testmon_data.read_source()
    testmon.start()
    func()
    testmon.stop_and_save(testmon_data, testdir.tmpdir.strpath, 'testnode')
    return testmon_data._fetch_node_data()[0]['testnode'], testmon, testmon_data


def test_run_deleted_code(testdir):
    a = testdir.makepyfile(a="""\
    def fun1():
        return 1

    def fun2():  # pragma: no cover
        return 1
    """)

    def f():
        coveragetest.import_local_file('a')

    deps, testmon, testmon_data = track_multiple(testdir, f)
    assert os.path.relpath(a.strpath, testdir.tmpdir.strpath) in deps
    assert len(deps) == 1

    deps, testmon, testmon_data = track_multiple(testdir, f, testmon, testmon_data)
    assert not deps

    a = testdir.makepyfile(a="""\
    def fun1():
        return 1
    """)

    deps, testmon, testmon_data = track_multiple(testdir, f, testmon, testmon_data)
    assert os.path.relpath(a.strpath, testdir.tmpdir.strpath) in deps
    assert len(deps) == 1

```

**Comment by tarpas** [comment] 2017-06-17 19:01
@TauPan I couldn't reproduce it. I tried with:
```
    def test_nocoverage_remove(self, testdir, monkeypatch):
        """"
        """
        test_a = testdir.makepyfile(test_a="""
            def test_fun1():
                assert True
                
            def test_nocoverage(): # pragma: no cover
                assert 1 + 2 == 3
        """)

        result = testdir.runpytest("--testmon")
        result.stdout.fnmatch_lines([
            "*2 passed*",
        ])

        test_a = testdir.makepyfile(test_a="""
            def test_fun1():
                assert True
        """)

        test_a.setmtime(1424880935)
        result = testdir.runpytest("-v", "--testmon", "--capture=no")
        result.stdout.fnmatch_lines([
            "*1 passed*",
        ])
```
And that's passing. Also after reading about the # pragma : no cover I think it's not relevant. Can you reproduce it with simple test files?

**Comment by maxim-lian** [comment] 2018-01-04 20:38
FYI I'm getting this every time I attempt to run testmon. It's on an inherited class. 

I'll post again if I can find any more basic cases that would help isolate the issue

**Comment by tarpas** [comment] 2018-09-14 09:09
Did you guys see this in recent months? I think it should be resolved with earlier refactoring.

**Comment by TauPan** [comment] 2018-09-14 09:12
Didn`t see  this in quite a while now. Thanks!

**Comment by tarpas** [comment] 2018-09-14 10:15
Thanks!

**Closed by tarpas** 2018-09-14 10:15 UTC
